name = "calorie-counter"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "calorie-counter"
vars = { BACKEND_URL = "https://belac-fun.up.railway.app" }

[env.development]
vars = { BACKEND_URL = "http://localhost:3000" }

# Serve frontend static files
[site]
bucket = "../frontend/dist"

[[env.production.routes]]
pattern = "calorie-counter.calebbadassbelac.workers.dev/*"
zone_name = "calebbadassbelac.workers.dev"
