name = "calorie-counter-worker"
main = "src/index.js"
type = "service"
compatibility_date = "2024-01-01"

[vars]
DATABASE_URL = "postgresql://postgres:TThUlTbUwJYVDgMWWiKOgsKcbLtoNoFk@switchyard.proxy.rlwy.net:45864/railway"
